USGS-CIDA/nwc

nwc/pom.xml, nwc/src/main/webapp/js/controller/NWCRouter.js, nwc/src/main/webapp/js/view/StreamflowStatsMapView.js
Added some temporary views for the streamflow-stats data pages
=> Watersmart 491

nwc/pom.xml
Things to note:
I changed the joinProtocols call in AquaticBiologyMapSelectView so that the GetFeature control would only fire one featuresselected event per operation rather than three.
I will be adding jasmine-jquery plugin to make loading templates and testing jquery selectors simpler during tests. I will also be refactoring the water budget and streamflow stats pages to update the view's html when handing model updates. I was only updating the map, but the buttons on the page reflect the state of the control's and those need to be updated too.
=> Updated test order dependancy

nwc/pom.xml, nwc/src/main/webapp/js/controller/NWCRouter.js, nwc/src/main/webapp/js/init.js, nwc/src/main/webapp/js/utils/templateLoader.js, nwc/src/main/webapp/js/view/BaseSelectMapView.js, nwc/src/main/webapp/js/view/BaseView.js, nwc/src/main/webapp/js/view/StreamflowStatsMapView.js, nwc/src/main/webapp/js/view/WaterBudgetMapView.js, nwc/src/main/webapp/templates/partials/warningModal.html, nwc/src/main/webapp/templates/streamflowStats.html, nwc/src/main/webapp/templates/waterbudget.html, nwc/src/test/javascript/specs/BaseSelectMapView_spec.js, nwc/src/test/javascript/specs/BaseView_spec.js, pom.xml
In addition to adding a modal warning, I instantiated the view's models in the router so that state can be restored when using the back button. Also added code to save the map extent so it too can be restored.
=> Watersmart 493

nwc/pom.xml, nwc/src/main/resources/application.properties, nwc/src/main/webapp/WEB-INF/USGSHead.jsp, nwc/src/main/webapp/WEB-INF/base.jsp, nwc/src/main/webapp/css/custom.css, nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/utils/mapUtils.js, nwc/src/main/webapp/js/view/BaseSelectMapView.js, nwc/src/main/webapp/js/view/BaseView.js, nwc/src/main/webapp/js/view/StreamflowStatsMapView.js, nwc/src/main/webapp/js/view/WaterBudgetMapView.js, nwc/src/main/webapp/templates/aquaticBiology.html, nwc/src/main/webapp/templates/streamflowStats.html, nwc/src/main/webapp/templates/waterbudget.html, nwc/src/test/javascript/specs/BaseSelectMapView_spec.js, pom.xml
Using the search data service rather then the javascript search API out of txpub. I'm going to go ahead and merge this so Blodgett can see how it works.  There will be some clean-up that needs to be done including put the search data service endpoint into context.xml.
=> Watersmart 474

nwc/src/main/webapp/js/utils/dataSeriesStore.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/test/javascript/specs/WaterBudgetHucDataView_spec.js
- modifications based on previous comments
- added WaterBudgetHucDataView.spec but it is mostly commented out.  
Couldn't figure out how to "stub" the options variable but would like to get this code merged for now.
=> Watersmart 494

nwc/pom.xml, nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/controller/NWCRouter.js, nwc/src/main/webapp/js/init.js, nwc/src/main/webapp/js/utils/hucCountiesIntersector.js, nwc/src/main/webapp/js/utils/mapUtils.js, nwc/src/main/webapp/js/view/HucCountyMapView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/main/webapp/templates/countyHucMap.html, nwc/src/main/webapp/templates/countyHucTable.html, nwc/src/main/webapp/templates/statsResults.html, nwc/src/main/webapp/templates/waterbudgetHucData.html, nwc/src/test/javascript/specs/WaterBudgetHucDataView_spec.js
For the moment, I have the route for the county page using the WaterBudgetHucDataView. This will have to change. Mark, you should also be able to use hucCountiesIntersector.js to display the percentages on the huc/county data page.
=> Watersmart 495

nwc/src/main/webapp/js/utils/SosSources.js
=> Updated eta SOS filename to HUC12_eta.nc

nwc/src/main/webapp/js/utils/CountyWaterUseProperties.js, nwc/src/main/webapp/js/view/WaterBudgetHucCountyDataView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/test/javascript/specs/WaterBudgetHucCountyDataView_spec.js, nwc/src/test/javascript/specs/WaterUsageChart_spec.js
- completed tests for watersmart-496
- some cleanup made while working on tests
=> Watersmart 496

nwc/src/main/webapp/js/utils/hucCountiesIntersector.js, nwc/src/main/webapp/js/utils/mapUtils.js, nwc/src/main/webapp/js/utils/streamStats.js, nwc/src/main/webapp/js/view/AquaticBiologyMapView.js, nwc/src/main/webapp/js/view/HucCountyMapView.js, nwc/src/main/webapp/js/view/StreamflowStatsGageDataView.js, nwc/src/main/webapp/js/view/StreamflowStatsHucDataView.js, nwc/src/main/webapp/js/view/StreamflowStatsMapView.js, nwc/src/main/webapp/js/view/WaterBudgetHucCountyDataView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/main/webapp/js/view/WaterBudgetMapView.js, nwc/src/main/webapp/templates/aquaticBiologySelectFeatures.html
I'll have another round of changes for the national HUCs once those are all loaded up. Wanted to get this into the canonical code before more work happens though.
=> Changes for counties and HUCs in postgis

nwc/src/main/webapp/WEB-INF/base.jsp, nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/init.js, nwc/src/main/webapp/js/view/DataDiscoveryView.js, nwc/src/main/webapp/templates/allProjects.html, nwc/src/main/webapp/templates/dataDiscovery.html, nwc/src/main/webapp/templates/partials/allProjects.html
This should work but I can't connect to the web service to test locally.  This will line will need to be added to context.xml to work locally:
<Environment name="nwc.endpoint.sciencebase" override="true" type="java.lang.String" value="https://beta.sciencebase.gov"/>
=> watersmart-507; initial review

nwc/src/main/webapp/templates/projectDetail.html
minor modification to handlebar template
=> Watersmart 508

nwc/src/main/webapp/js/view/AquaticBiologyMapView.js, nwc/src/main/webapp/js/view/StreamflowStatsMapView.js, nwc/src/main/webapp/templates/streamflowHucStats.html, nwc/src/main/webapp/templates/streamflowStats.html
Getting a new layer incorporated for visualizing and selecting watersheds. Still using the other one for the WFS of the actual selected watershed though. Also mucked around with the preliminary text and link. There's a journal pub out for the data now so we can do this.
=> Se huc changes

nwc/src/main/webapp/css/custom.css, nwc/src/main/webapp/js/model/AquaticBiologyFeaturesModel.js, nwc/src/main/webapp/js/view/AquaticBiologyMapView.js, nwc/src/main/webapp/js/view/AquaticBiologySelectFeaturesView.js, nwc/src/main/webapp/js/view/BiodataGageMapView.js, nwc/src/main/webapp/templates/aquaticBiologySelectFeatures.html, nwc/src/test/javascript/specs/AquaticBiologySelectFeaturesView_spec.js
@mbucknell , I got the map selections working!  Can you please review when you have time?
=> Watersmart 517

nwc/src/main/webapp/js/view/DataDiscoveryView.js, nwc/src/main/webapp/templates/dataDiscoveryDetail.html, nwc/src/main/webapp/templates/dataDiscoveryList.html
This will need more work but merging so Dave can take a look at the current state and provide feedback.
=> watersmart-428; iterating through display

nwc/src/main/webapp/js/controller/NWCRouter.js, nwc/src/main/webapp/js/view/DataDiscoveryView.js, nwc/src/main/webapp/js/view/HomeView.js, nwc/src/main/webapp/js/view/ProjectView.js, nwc/src/main/webapp/templates/dataDetail.html, nwc/src/main/webapp/templates/dataDiscovery.html, nwc/src/main/webapp/templates/projectDetail.html
@mbucknell - This seems to work but let me know if you see any better practices I should use.  It also seems like the tab views could be refactored into three distinct views rather than being "sub" views of the DataDiscovery view.  That way each list would be refreshed when clicking on the tab, and possibly simplify the design.  However, for this iteration I took the approach of minimal change to engage the backbone history.
=> Watersmart 524

nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/controller/NWCRouter.js, nwc/src/main/webapp/js/init.js, nwc/src/main/webapp/js/utils/templateLoader.js, nwc/src/main/webapp/js/view/HucInsetMapView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/main/webapp/templates/hucCompareInsetMapContainer.html, nwc/src/main/webapp/templates/hucComparePlotViewContainer.html, nwc/src/main/webapp/templates/hucInsetMap.html, nwc/src/main/webapp/templates/waterbudgetHucData.html, nwc/src/test/javascript/specs/WaterBudgetHucDataView_spec.js, nwc/src/test/javascript/specs/templateLoader_spec.js
Created a new subView, HucInsetMapView, and used it to create the water budget huc data page huc inset map. If we are comparing hucs then two inset maps are shown.
=> Watersmart 528

nwc/src/main/webapp/js/view/BaseDiscoveryTabView.js, nwc/src/main/webapp/js/view/DataView.js, nwc/src/main/webapp/js/view/ProjectView.js
@mbucknell - Just a first pass to see if the approach is ok.  If so, is this "enough" or should I extend this approach to the project and data detail pages.  Also, I'm not sure whether or not Dave will want the error message displayed as I have it now (which use to show up in an alert), so I may need to remove that.
=> watersmart-550; initial commit for task

nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/utils/openLayersExtensions/OpenLayersIE11Fix.js, nwc/src/main/webapp/js/view/AquaticBiologySelectFeaturesView.js, nwc/src/main/webapp/templates/aquaticBiologySelectFeatures.html
Trying out a fix to an IE11 WFS GetFeature call. I had to do the same thing in NAR.
=> Watersmart 541

pom.xml
Now plugin will cache phantomjs download.
=> Speeding up tests by upgrading phantomjs maven plugin. 

nwc/pom.xml
Can opt out via:
```
mvn clean install -P \!generate-search-engine-files-mac-and-linux
```
=> Making search engine file generation opt-out, hardcoding param.

nwc/src/main/webapp/js/view/BaseSelectMapView.js, nwc/src/main/webapp/js/view/WaterBudgetMapView.js, nwc/src/test/javascript/specs/WaterBudgetMapView_spec.js
@mbucknell - I found the problem with the duplicate layers, which was that I was creating duplicate layers....go figure.  I'm not sure why this wasn't happening before I added the huc8 layer.  Regardless, would you take a look and see if I am handling the best way.
=> Watersmart 546

nwc/src/main/webapp/js/model/Config.js, nwc/src/main/webapp/js/utils/streamStats.js, nwc/src/main/webapp/js/view/StreamflowStatsGageDataView.js
Added config for the statistics service into the Config model as well as the the services to retrieve NWIS site file and streamflow data.
=> More config changes

nwc/src/main/webapp/js/model/Config.js, nwc/src/main/webapp/js/utils/mapUtils.js, nwc/src/main/webapp/js/view/AquaticBiologyMapView.js
I've changed all these on wsdev and will procede to qa once tested.
=> changes that should fix the QA issue with cida-test rewrites

nwc/src/main/webapp/js/model/Config.js, nwc/src/main/webapp/js/utils/mapUtils.js
For HUC08s the text size was too large. I need to push this out so I turned accumulated back off.
=> text size change for HUC08 county comparison

nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/model/Config.js
@mbucknell I verified that this shows up in the page that loads initially, is this what you would expect?
=> IE11 meta tag and prepare to re-release

README.md
looks like the 1.0 version of the API is dead
=> texas API version change

nwc/src/main/webapp/css/custom.css, nwc/src/main/webapp/js/view/HucInsetMapView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/main/webapp/js/view/WaterbudgetPlotView.js, nwc/src/main/webapp/templates/hucInsetMap.html
Layout changes and label adjustments needed after adding the streamflow data to the accumulated water budget pages.
=> Watersmart 589

nwc/pom.xml, nwc/src/main/webapp/WEB-INF/web.xml, nwc/src/main/webapp/css/custom.css, nwc/src/main/webapp/index.jsp, nwc/src/main/webapp/js/init.js, nwc/src/main/webapp/js/model/WaterBudgetHucPlotModel.js, nwc/src/main/webapp/js/utils/dataSeriesStore.js, nwc/src/main/webapp/js/utils/executeFeatureTSCollection.js, nwc/src/main/webapp/js/view/CountyWaterUseView.js, nwc/src/main/webapp/js/view/HucInsetMapView.js, nwc/src/main/webapp/js/view/WaterBudgetHucDataView.js, nwc/src/main/webapp/js/view/WaterbudgetDownloadUpstreamView.js, nwc/src/main/webapp/js/view/WaterbudgetPlotView.js, nwc/src/main/webapp/templates/waterbudgetDownloadUpstream.html, nwc/src/main/webapp/templates/waterbudgetHucData.html, nwc/src/main/webapp/templates/xml/FeatureTimeSeriesCollection.xml, nwc/src/main/webapp/vendorlibs/jquery.download.js, nwc/src/test/javascript/specs/WaterBudgetHucDataView_spec.js, nwc/src/test/javascript/specs/WaterbudgetPlotView_spec.js
Biggest change besides adding the requested feature, was moving the dataseriesStore into the WaterBudgetPlotModel. This way it is easy to distinguish between the dataseriesStore for the first huc on a page and the compare huc. This also became a logical place to put the modeledWatershedAcres. This refactoring made it simpler to add the new feature.
I did not add tests for the new modules. The executeFeatureTsCollection in utils loads a template at intialization making it hard to test. The WaterbudgetDownloadUpstreamView is also challenging to test due to having to pass in a mockedthe dataseriesstore in the model.  This view is actually pretty straightforward as the hard work is down in executeFeatureTsCollection.
=> Watersmart 608
